// vue-frontend/src/components/GraphicList.vue
<template>
    <div
      :style="{
        borderRadius: border_radius + 'px',
        height: height + 'px',
        width: width + 'px',
        backgroundColor: 'black'
      }"
    >
      <Graphic v-for="graph in graphic" :key="graph.id" :graph="graph" />
    </div>
  </template>
  
  <script>
  import Graphic from "./Graphic.vue";
  
  export default {
    components: {
      Graphic
    },
    props: {
      graphic: {
        type: Array,
        required: true
      },
      border_radius: {
        type: Number,
        default: 0
      },
      height: {
        type: Number,
        default: 100
      },
      width: {
        type: Number,
        default: 100
      }
    }
  };
  </script>
  
  <style scoped>
  /* You can add scoped styles here if needed */
  </style>

// react-frontend/src/components/GraphicList.jsx
import React from "react";

import Graphic from "./Graphic";

const GraphicList = (props) => {
  return (
    <div
      style={{
        border_radius: props.border_radius,
        height: props.height,
        width: props.width,
        backgroundColor: "black",
      }}
    >
      {props.graphic.map((graph) => (
        <Graphic
          key={graph.id}
          num={graph.num}
          layer={graph.layer}
          height={graph.height}
          width={graph.width}
          x_axis={graph.x_axis}
          y_axis={graph.y_axis}
          border_weight={graph.border_weight}
          border_color={graph.border_color}
          border_radius={graph.border_radius}
          font_size={graph.font_size}
          font_weight={graph.font_weight}
          note={graph.note}
          created_at={graph.created_at}
        />
      ))}
    </div>
  );
};

export default GraphicList;
