// react-frontend/src/components/AddGraphic.jsx
import React, { useRef } from "react";

// import classes from './AddMovie.module.css';

function AddGraphic(props) {
  const titleRef = useRef("");
  const openingTextRef = useRef("");
  const releaseDateRef = useRef("");

  function submitHandler(event) {
    event.preventDefault();
    const graph = {
      title: titleRef.current.value,
      openingText: openingTextRef.current.value,
      releaseDate: releaseDateRef.current.value,
    };

    props.onGraphic(graph);
  }

  return (
    <form onSubmit={submitHandler}>
      <div>
        {/* <label htmlFor='opening-text'>Opening Text</label> */}
        <input type="text" id="note" ref={openingTextRef}></input>
      </div>
      <button>Add Graphic</button>
    </form>
  );
}

export default AddGraphic;

// vue-frontend/src/components/AddGraphic.vue
<template>
    <form @submit.prevent="submitHandler">
      <div>
        <!-- <label for="opening-text">Opening Text</label> -->
        <input type="text" id="note" v-model="note" />
      </div>
      <button type="submit">Add Graphic</button>
    </form>
  </template>
  
  <script>
  export default {
    data() {
      return {
        note: "",
      };
    },
    methods: {
      submitHandler() {
        const graphic = {
          title: "", // You may add title and releaseDate if required
          openingText: this.note,
          releaseDate: "",
        };
        this.$emit("onAddMovie", graphic);
        this.note = ""; // Reset note after submission if needed
      },
    },
  };
  </script>
